# 'default' profile always gets included on all install profiles
default = [
    # provider selections for dependencies
    "pipewire-jack",
    "qt6-multimedia-ffmpeg",
    "cronie",
    "noto-fonts-emoji",
    "clipman",
    "noto-fonts",
    "vulkan-intel",
    "lib32-vulkan-intel",

    # terminal & system utils
    "bandwhich",
    "bat",
    "bind",
    "biodiff",
    "bottom",
    "curlie",
    "downgrade",
    "duf",
    "dust",
    "eza",
    "fd",
    "fzf",
    "git",
    "git-lfs",
    "github-cli",
    "gum",
    "hexyl",
    "httpie",
    "hyperfine",
    "imagemagick",
    "jq",
    "lazygit",
    "macchina",
    "man-db",
    "neovim",
    "ntfs-3g",
    "openresolv",
    "openssh",
    "pacman-contrib",
    "pam-u2f",
    "procs",
    "python-uv",
    "reflector",
    "ripgrep",
    "rustup",
    "samba",
    "sd",
    "smartmontools",
    "smbclient",
    "speedtest-cli",
    "sudo",
    "tokei",
    "ufw",
    "unrar",
    "unzip",
    "vivid",
    "wget",
    "wireguard-tools",
    "xdg-user-dirs",
    "yt-dlp",
    "zip",
    "zoxide",
    "zsh",

    # GUI apps & utils
    "apple_cursor",
    "ark",
    "chromium",
    "clipman",
    "cifs-utils",
    "discord",
    "electrum",
    "firefox",
    "git-credential-keepassxc",
    "gnucash",
    "handlr-regex",
    "hunspell-en_us",
    "kde-graphics-meta",
    "kde-system-meta",
    "keepassxc",
    "kitty",
    "libreoffice-fresh",
    "obsidian",
    "pavucontrol",
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "plasma-desktop",
    "qalculate-qt",
    "realtime-privileges",
    "sddm",
    "sddm-kcm",
    "spotify-launcher",
    "syncthing",
    "ttf-jetbrains-mono",
    "ttf-nerd-fonts-symbols",
    "vlc",
    "wireplumber",
    "yubikey-manager"
]
workstation = [
    # provider selections for dependencies
    "noto-fonts",
    "vulkan-intel",
    "lib32-vulkan-intel",

    "blender",
    # "davinci-resolve",
    "discover",
    "flatpak",
    "flatpak-kcm",
    "gimp",
    "handbrake",
    "inkscape",
    "kexec-tools",
    "looking-glass",
    "mesa-utils",
    "nfs-utils",
    "obs-plugin-looking-glass",
    "obs-studio",
    "ocenaudio-bin",
    "steam-devices-git",
    "virt-manager",
    "wine-mono",
    "winetricks",
    "yabridge",
    "yabridgectl"
]
laptop = [
    "acpi",
    "bluez",
    "brightnessctl",
    "tlp"
]
